=== jsueiras/mash/mash-model/src/main/resources/mashModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mash.data.com/mashModel" 
xmlns:tns="http://www.mash.data.com/mashModel"
 xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.0"
  xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
  jaxb:extensionBindingPrefixes="xjc" elementFormDefault="qualified">

  <annotation>
        <appinfo>
            <jaxb:globalBindings>
                <xjc:simple />
            </jaxb:globalBindings>
        </appinfo>
    </annotation>
   <complexType name="Root" abstract="true">
       <sequence>
          <element name="id" type="string" minOccurs="0"></element>
       </sequence>
   </complexType>
   <complexType name="Act" abstract="true">
     <complexContent>
   		<extension base="tns:Root">
        <sequence>
   		    <element name="ocurrenceDate" type="date" minOccurs="0"></element>
   	        <element name="participants" type="tns:Participations" minOccurs="0"></element>
   	   </sequence>
   	   </extension>
   	   </complexContent>
   </complexType>
   <complexType name="Entity" abstract="true">
      <complexContent>
   		<extension base="tns:Root">
      </extension>
      </complexContent>		
   </complexType>
     <complexType name="EntitySummary" abstract="true">
      <complexContent>
   		<extension base="tns:Entity">
    		<sequence>
   			    <element name="type" type="string" minOccurs="1"/>
   				 <element name="attributes" type="tns:Entry" minOccurs="0" maxOccurs="unbounded"/>
   			</sequence>
       </extension>
      </complexContent>		
   </complexType>
   <complexType name="Role" abstract="true">
       <sequence>
           <element name="from" type="date" minOccurs="0"></element>
   		   <element name="to" type="date" minOccurs="0"></element>
       </sequence>
   </complexType>
     
     <complexType name="Relation" abstract="true">
      <complexContent>
   		<extension base="tns:Role">
   		   <sequence>
   		      <element ref="tns:person"/>
   		   </sequence>
      </extension>
      </complexContent>		
   </complexType>
   
   
     <complexType name="Parent">
      <complexContent>
   		<extension base="tns:Relation">
   		   
      </extension>
      </complexContent>		
   </complexType>
    <complexType name="Child">
      <complexContent>
   		<extension base="tns:Relation">
   		   
      </extension>
      </complexContent>		
   </complexType>
    <complexType name="OtherRelation">
    	<complexContent>
    		<extension base="tns:Relation">
                <sequence>
                  <element name="type" type="string" minOccurs="1"/>
                </sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Sibiling">
      <complexContent>
   		<extension base="tns:Relation">
   		   
      </extension>
      </complexContent>		
   </complexType>
   
    <complexType name="Participation" abstract="true">
       
   </complexType>
   
    <complexType name="GenericParticipant" >
      <complexContent>
   		<extension base="tns:Participation">
   		    <choice>
   		      <element ref="tns:act"/>
   		      <element ref="tns:entity"/>
   		   </choice>
      </extension>
      </complexContent>	
   </complexType>
   <complexType name="Victim">
      <complexContent>
   		<extension base="tns:Participation">
   		   <choice>
   		      <element ref="tns:crime"/>
   		      <element ref="tns:person"/>
   		   </choice>
      </extension>
      </complexContent>		
   </complexType>
   
    <complexType name="SubjectOf">
      <complexContent>
   		<extension base="tns:Participation">
   		   <choice>
   		      <element ref="tns:referral"/>
   		      <element ref="tns:person"/>
   		   </choice>
      </extension>
      </complexContent>		
   </complexType>

  <complexType name="Crime">
   	<complexContent>
   		<extension base="tns:Act">
   			
   		</extension>
   	</complexContent>
   </complexType>
   
    <complexType name="ActSummary">
   	<complexContent>
   		<extension base="tns:Act">
   			<sequence>
   			    <element name="type" type="string" minOccurs="1"/>
   				 <element name="attributes" type="tns:Entry" minOccurs="0" maxOccurs="unbounded"/>
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>
   <complexType name="Referral">
   	<complexContent>
   		<extension base="tns:Act">
   			<sequence>
   			    <element name="type" type="string" minOccurs="0"/>
   				<element name="comments" type="string" minOccurs="0" maxOccurs="unbounded" />
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>
   
  
   
    <complexType name="Person">
   	<complexContent>
   		<extension base="tns:Entity">
   			<sequence>
   				<element name="firstName" type="string" minOccurs="0"></element>
   				<element name="lastName" type="string" minOccurs="0"></element>
   				<element name="dateOfBirth" type="date" minOccurs="0"></element>
   				<element name="gender" type="string" minOccurs="0"></element>
   				<element name="homeAddress" type="tns:Address" minOccurs="0"></element>
   				<element name="participations" type="tns:Participations" minOccurs="0"></element>
   				<element name="household" type="tns:Household" minOccurs="0"></element>
   				<element name="otherAddresses" type="tns:Address" minOccurs="0" maxOccurs="unbounded"></element>
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>
   
    <complexType name="Address">
   	<complexContent>
   		<extension base="tns:Role">
   			<sequence>
   				<element name="location" type="tns:Location" minOccurs="1"></element>
   				<element name="type" type="string" minOccurs="0"></element>
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>
   
    <complexType name="Occupant">
   	<complexContent>
   		<extension base="tns:Role">
   			<sequence>
   				<element name="person" type="tns:Person" minOccurs="1"></element>
   				<element name="type" type="string" minOccurs="0"></element>
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>
   
   <complexType name="Location">
   	<complexContent>
   		<extension base="tns:Entity">
   			<sequence>
   				<element name="uprn" type="string" minOccurs="0"></element>
   				<element name="numberOrName" type="string"  minOccurs="0"></element>
   				<element name="street" type="string" minOccurs="0"></element>
   				<element name="city" type="string"  minOccurs="0"></element>
   				<element name="county" type="string"  minOccurs="0"></element>
   				<element name="postcode" type="string"  minOccurs="0"></element>
   				<element name="occupants" type="tns:Occupant" minOccurs="0" maxOccurs="unbounded"></element>
   			</sequence>
   		</extension>
   	</complexContent>
   </complexType>


  
 
     <element name="locations" type="tns:Locations"/>
    
   <element name="persons" type="tns:Persons"/>
  
   <element name="entities" type="tns:Entities"/>
  
   
     
 
   
  <complexType name="Participations">
     <sequence>
        <element ref="tns:participation"  minOccurs="0" maxOccurs="unbounded"></element>
     </sequence>
  </complexType>
  
    
  <complexType name="Persons">
     <sequence>
        <element ref="tns:person"  minOccurs="0" maxOccurs="unbounded"></element>
     </sequence>
  </complexType>
  
  <complexType name="Locations">
     <sequence>
        <element ref="tns:location"  minOccurs="0" maxOccurs="unbounded"></element>
     </sequence>
  </complexType>
  
   <complexType name="Entities">
     <sequence>
        <element ref="tns:entity"  minOccurs="0" maxOccurs="unbounded"></element>
     </sequence>
  </complexType>
  
   <complexType name="Household">
     <sequence>
        <element ref="tns:relation"  minOccurs="0" maxOccurs="unbounded"></element>
     </sequence>
  </complexType>
  
   <element name="act" abstract="true" type="tns:Act"/>
   <element name="crime" type="tns:Crime" substitutionGroup="tns:act"/>
   <element name="referral" type="tns:Referral" substitutionGroup="tns:act"/>
    <element name="actSummary" type="tns:ActSummary" substitutionGroup="tns:act"/>
   
   <element name="entity" abstract="true" type="tns:Entity"/>
   <element name="person" type="tns:Person" substitutionGroup="tns:entity"/>
   <element name="location" type="tns:Location" substitutionGroup="tns:entity"/>
   <element name="entitySummary" type="tns:EntitySummary" substitutionGroup="tns:entity"/>
    
  
    
    
    <element name="relation" abstract="true" type="tns:Relation"/>
   
    
    <element name="parent" type="tns:Parent" substitutionGroup="tns:relation"/>
    <element name="child" type="tns:Child" substitutionGroup="tns:relation"/>
   
    <element name="sibiling" type="tns:Sibiling" substitutionGroup="tns:relation"/>
    <element name="otherRelation" type="tns:OtherRelation" substitutionGroup="tns:relation"/>
 
   <element name="participation" abstract="true" 
             type="tns:Participation"/>
   
   <element name="victim" substitutionGroup="tns:participation" 
             type="tns:Victim"/>
   <element name="subjectOf" substitutionGroup="tns:participation" 
             type="tns:SubjectOf"/>
    <element name="generic" substitutionGroup="tns:participation" 
             type="tns:GenericParticipant"/>          
             
 
  
     <complexType name="Entry">
           <sequence>
                <element name="key" minOccurs="1" type="string"/>
                 <element name="value" minOccurs="0" type="string"/>
           </sequence>
     </complexType>
</schema>

=== jsueiras/mash/mash-model/src/main/resources/bartsimpson.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<persons xmlns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
    <person>
     <id>bart</id>
	<firstName>Bart</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1979-04-01</dateOfBirth>
    <gender>Male</gender>
	<homeAddress>
	   <location>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
	<household>
	<relation>
	<type>Mother</type>
	<person>
	 <id>marge</id>
	<firstName>Marge</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1954-03-19</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
</person>
</relation>
<relation>
  <type>Father</type>
<person>
	 <id>homer</id>
	<firstName>Homer</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1955-05-12</dateOfBirth>
    <gender>Male</gender>
	<homeAddress>
	   <location>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
</person>
</relation>
<relation>
  <type>Sibiling</type>
	<person>
	 <id>lisa</id>
	<firstName>Lisa</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1981-09-28</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
</person>
</relation>
<relation>
    <type>Sibiling</type>
	<person>
	 <id>maggie</id>
	<firstName>Maggie</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1989-01-12</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
</person>
</relation>
</household>
</person>
</persons>

=== jsueiras/mash/mash-model/src/main/resources/springfield.xml
<?xml version="1.0" encoding="UTF-8"?>
<locations xmlns="http://www.mash.data.com/mashModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
    <location>
       <id>homeraddress</id>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
		<postcode>28003</postcode>
	  </location>
	  <location>
       <id>flandersaddress</id>
	   <numberOrName>744</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
		<postcode>28003</postcode>
	  </location>	
</locations>

=== jsueiras/mash/mash-model/src/main/resources/bart2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<person xmlns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
     <id>bart2</id>
	<firstName>Bart</firstName>
	<lastName>Sampson</lastName>
	<dateOfBirth>2005-04-01</dateOfBirth>
    <gender>Male</gender>
	<homeAddress>
	   <location>
	   <id>springfield747</id>
	  </location>	
	</homeAddress>
	<household>
	<relation>
	<type>son</type>
	<person>
	 <id>marge2</id>
</person>
</relation>
<relation>
  <type>son</type>
<person>
	 <id>homer2</id>
</person>
</relation>
<relation>
  <type>grandson</type>
	<person>
	 <id>granma</id>
</person>
</relation>
<relation>
    <type>halfbrother</type>
	<person>
	 <id>maggie2</id>
</person>
</relation>
<relation>
    <type>halfbrother</type>
	<person>
	 <id>lisa2</id>
</person>
</relation>
</household>
</person>

=== jsueiras/mash/mash-data-services/src/main/resources/personList.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tns:persons xmlns:tns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
<tns:person>
    <tns:id>person1</tns:id>
	<tns:firstName>first</tns:firstName>
	<tns:lastName>dfdfsda</tns:lastName>
	<tns:homeAddress>
	   <tns:location>
		<tns:city>Sutton</tns:city>
	  </tns:location>	
	</tns:homeAddress>
</tns:person>
</tns:persons>

=== jsueiras/mash/mash-model/src/main/resources/lisa.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<person xmlns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
   <id>lisa</id>
	<firstName>Lisa</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>2007-09-28</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <id>springfield742</id>
	  </location>	
	</homeAddress>
	<household>
	<relation>
	<type>daughter</type>
	<person>
	 <id>marge</id>
</person>
</relation>
<relation>
  <type>daughter</type>
<person>
	 <id>homer</id>
</person>
</relation>
<relation>
  <type>sibiling</type>
	<person>
	   <id>bart</id>
</person>
</relation>
<relation>
    <type>sibiling</type>
	<person>
	 <id>maggie</id>
</person>
</relation>
</household>
</person>

=== jsueiras/mash/mash-model/src/main/resources/marge.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<person xmlns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
	 <id>marge</id>
	<firstName>Marge</firstName>
	<lastName>Simpson</lastName>
	<dateOfBirth>1954-03-19</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <id>springfield742</id>
	   <numberOrName>742</numberOrName>
	    <street>Evergreen Terrace</street>
		<city>Springfield</city>
	  </location>	
	</homeAddress>
	<household>
	<relation>
	<type>married</type>
	<person>
	  <id>homer</id>
</person>
</relation>
<relation>
  <type>mother</type>
<person>
	 <id>bart</id>
</person>
</relation>
<relation>
  <type>mother</type>
	<person>
	 <id>lisa</id>
</person>
</relation>
<relation>
    <type>mother</type>
	<person>
	 <id>maggie</id>
</person>
</relation>
</household>
</person>

=== jsueiras/mash/mash-model/src/main/resources/maggie2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<person xmlns="http://www.mash.data.com/mashModel" schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
     <id>maggie2</id>
	<firstName>Maggie</firstName>
	<lastName>Clown</lastName>
	<dateOfBirth>2014-01-12</dateOfBirth>
    <gender>Female</gender>
	<homeAddress>
	   <location>
	   <id>springfield745</id>
	  </location>	
	</homeAddress>
	<household>
	<relation>
	<type>daughter</type>
	<person>
	 <id>marge2</id>
</person>
</relation>
<relation>
  <type>daughter</type>
<person>
	 <id>krusty</id>
</person>
</relation>
<relation>
  <type>sibiling</type>
	<person>
	 <id>lisa2</id>
</person>
</relation>
<relation>
    <type>halfsister</type>
	<person>
	 <id>bart2</id>
</person>
</relation>
<relation>
    <type>granddaughter</type>
	<person>
	 <id>granma</id>
</person>
</relation>
</household>
</person>

=== jsueiras/mash/mash-model/src/main/resources/mashModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:person xmlns:tns="http://www.mash.data.com/mashModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mash.data.com/mashModel mashModel.xsd ">
  <tns:id>tns:id</tns:id>
   <tns:firstName></tns:firstName>
   <tns:lastName></tns:lastName>
   <tns:homeAddress>
       <tns:id>addressId</tns:id>
   </tns:homeAddress>
   <tns:participations>
       <tns:subjectOf>
           <tns:referral>
               <tns:id>xxx</tns:id>
           </tns:referral>
       </tns:subjectOf>
       <tns:victim>
             <tns:crime>
                 <tns:id>xxxx</tns:id>
             </tns:crime>
       </tns:victim>
   </tns:participations>
   <tns:household>
      <tns:parent>
         <tns:person>
             <tns:id>id_parent</tns:id>
         </tns:person>
      </tns:parent>
       <tns:parent>
         <tns:person>
             <tns:id>id_parent</tns:id>
         </tns:person>
      </tns:parent>
       <tns:sibiling>
         <tns:person>
             <tns:id>id_parent</tns:id>
         </tns:person>
      </tns:sibiling>
   </tns:household>
</tns:person>
